### ISSUE TITLE
update pre-existing paretoset

### ISSUE THREAD

**Issue by remiadon** [tommyod/paretoset#22]
For an optimisation problem I need to instantiate a paretoset and keep it up to date when new data comes in

With the current implementation my workflow looks like the following
```python
from paretoset import paretoset
import pandas as pd

my_set = pd.DataFrame(columns=["A", "B"])
for bunch in new_data_iterator:
    candidates = pd.concat(my_set, bunch, axis=0)
    idxs = paretoset(candidates, ["min", "max"])
    my_set = candidates[idxs]
```

The problem with the current implem is that the `paretoset` method returns a boolean mask. We cannot keep a mask up to date.

Is there any way of doing better ?

**Comment by tommyod** [comment]
There's no way to do better that I know of. 

Every new item must be checked against every existing item, since the new item could itself be in the paretoset (or not), and it could remove any existing item from the paretoset (or not). It's probably faster in practical terms to run the paretoset algorithm on a single dataframe once, instead of batching and updating, but that's because of the vectorization. The theoretical complexity (big-Oh) is the same either way.

I hope this answers you questions. If not, let me know.
