### ISSUE TITLE
Big-O time complexity

### ISSUE THREAD

**Issue by tanner-andrulis** [tommyod/paretoset#44]
Do you have an estimate for the big-O time complexity to calculate the pareto set of $N$ points in an $M$-dimensional space? I am working with a large number of points and looking for an $O(M\times Nlog(N))$ solution, such as one of the solutions discussed in this thread https://math.stackexchange.com/questions/500006/finding-pareto-optimal-solution-set-in-on-log-n-time .

Thank you!

**Comment by tommyod** [comment]
This implementation is $\mathcal{O}(N^2 M)$ in the worst case if I remember correctly. We use a simple algorithm in this library, where when adding each point we have to compare with N others, and each comparison costs M. So we have `M(1 + 2 + 3 ... N) = MN^2` In practice it's often much faster and that many operations do not need to be done, because we can short-circuit the comparisons in all but the most pathological cases.

Specialized algorithms for low dimensional data (N=2) etc do exist. Even relatively simple ones, I believe. I am not sure if there is an algorithm that is faster than `MN^2` for arbitrary N. Maybe, but if so it's probably complicated and harder to implement.

PRs are welcome, but there is a balance here between complexity of the algorithm, special cases for certain dimensions, and also practical speed vs big-Oh theoretical speed.

**Comment by tanner-andrulis** [comment]
Thank you, all excellent points. I've been searching more and have also been unable to find any $MNlogN$ algorithms for $N>2$. 

I plan on using paretoset for my project, and will submit a PR if I end up incorporating any optimizations that would be helpful to you (& consider the balance of complexity/special cases/speed as you described).

**Comment by MLopez-Ibanez** [comment]
> Thank you, all excellent points. I've been searching more and have also been unable to find any M N l o g N algorithms for M > 2 .

@tanner-andrulis  See https://multi-objective.github.io/moocore/python/reference/generated/moocore.is_nondominated.html and references therein.
